# Generated by Django 4.2.7 on 2023-11-16 06:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("BlogName", models.CharField(default="", max_length=100)),
                ("BlogDescription", models.CharField(default="", max_length=500)),
                ("BlogDateAdded", models.CharField(default="", max_length=20)),
                ("BlogImage", models.CharField(default="", max_length=500)),
                ("BlogSlug", models.CharField(default="", max_length=400)),
                (
                    "BlogCategory",
                    models.CharField(
                        choices=[
                            ("Stock Market", "Stock Market"),
                            ("Bitcoin", "Bitcoin"),
                            ("Trading", "Trading"),
                            ("Commerce", "Commerce"),
                            ("Business ideas", "Business idea"),
                            ("Crypto currency", "Crypto currency"),
                        ],
                        default="",
                        max_length=100,
                    ),
                ),
                ("BlogPost", models.TextField(default="", max_length=10000)),
                ("BlogAuthor", models.CharField(default="", max_length=50)),
                ("Views", models.CharField(default="0", max_length=50)),
                (
                    "Likes",
                    models.ManyToManyField(
                        blank=True,
                        related_name="UserLikes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BlogComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(default="", max_length=200)),
                ("Email", models.EmailField(default="", max_length=200)),
                ("Comment", models.TextField(default="", max_length=1000)),
                (
                    "Date",
                    models.CharField(
                        default="2023-11-16 12:21:35.966645", max_length=40
                    ),
                ),
                ("ActualDate", models.CharField(default="16-11-2023", max_length=40)),
                ("User_ProfilePhoto", models.CharField(default="", max_length=200)),
                (
                    "BlogDetails",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="BlogDet",
                        to="WhatsafBlogs.blog",
                    ),
                ),
                (
                    "UserDetails",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="CommentsUserDet",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
