# Generated by Django 4.2.7 on 2023-11-16 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("WhatsafBlogs", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blog",
            name="BlogCategory",
        ),
        migrations.AlterField(
            model_name="blogcomment",
            name="Date",
            field=models.CharField(default="2023-11-16 12:40:06.637671", max_length=40),
        ),
    ]
