# Generated by Django 4.2.7 on 2023-11-17 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("WhatsafBlogs", "0003_remove_blogcomment_user_profilephoto_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogcomment",
            name="User_ProfilePhoto",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="blogcomment",
            name="Date",
            field=models.CharField(default="2023-11-17 20:48:27.012290", max_length=40),
        ),
    ]
