# Generated by Django 4.2.7 on 2023-11-18 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("WhatsafBlogs", "0004_blogcomment_user_profilephoto_alter_blogcomment_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogcomment",
            name="ActualDate",
            field=models.CharField(default="18-11-2023", max_length=40),
        ),
        migrations.AlterField(
            model_name="blogcomment",
            name="Date",
            field=models.CharField(default="2023-11-18 19:25:57.161453", max_length=40),
        ),
    ]
