# Generated by Django 4.2.7 on 2023-11-11 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=100)),
                ("Email", models.EmailField(max_length=100)),
                ("Subject", models.CharField(max_length=500)),
                ("Message", models.TextField(max_length=2000)),
            ],
        ),
    ]
