# Generated by Django 4.2.7 on 2023-11-12 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("WhatsafPortal", "0002_userdetail"),
    ]

    operations = [
        migrations.AddField(
            model_name="userdetail",
            name="Premium",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userdetail",
            name="Verification",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="userdetail",
            name="DOB",
            field=models.DateField(default=""),
        ),
        migrations.AlterField(
            model_name="userdetail",
            name="ProfilePhoto",
            field=models.ImageField(default="", upload_to=""),
        ),
    ]
