# Generated by Django 4.2.7 on 2023-11-12 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("WhatsafPortal", "0003_userdetail_premium_userdetail_verification_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userdetail",
            name="Country",
            field=models.CharField(default="", max_length=100),
        ),
    ]
