# Generated by Django 4.2.7 on 2023-11-13 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("WhatsafPortal", "0006_remove_faq_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Feature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=1000)),
                ("Desc", models.TextField(max_length=1000)),
                ("Link", models.CharField(max_length=100)),
            ],
        ),
    ]
