# Generated by Django 4.2.7 on 2023-11-13 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("WhatsafPortal", "0007_feature"),
    ]

    operations = [
        migrations.AddField(
            model_name="feature",
            name="Image",
            field=models.CharField(default="", max_length=1000),
        ),
    ]
