# Generated by Django 4.2.7 on 2023-11-13 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("WhatsafPortal", "0009_alter_feature_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="feature",
            name="Beta",
            field=models.BooleanField(default=False),
        ),
    ]
