# Generated by Django 4.2.7 on 2023-11-13 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("WhatsafPortal", "0010_feature_beta"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feature",
            name="Beta",
            field=models.BooleanField(default=True),
        ),
    ]
