# Generated by Django 4.2.7 on 2023-11-13 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("WhatsafPortal", "0011_alter_feature_beta"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="feature",
            name="Beta",
        ),
        migrations.AddField(
            model_name="feature",
            name="Stable",
            field=models.BooleanField(default=False),
        ),
    ]
