# Generated by Django 4.2.7 on 2023-11-13 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("WhatsafPortal", "0013_alter_feature_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feature",
            name="Image",
            field=models.CharField(max_length=1000),
        ),
    ]
