# Generated by Django 4.2.7 on 2023-11-14 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("WhatsafPortal", "0014_alter_feature_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="userdetail",
            name="Monthly",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userdetail",
            name="Yearly",
            field=models.BooleanField(default=False),
        ),
    ]
