# Generated by Django 4.2.7 on 2023-11-14 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("WhatsafPortal", "0015_userdetail_monthly_userdetail_yearly"),
    ]

    operations = [
        migrations.AddField(
            model_name="userdetail",
            name="Trial",
            field=models.BooleanField(default=False),
        ),
    ]
