# Generated by Django 4.2.7 on 2023-11-15 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("WhatsafPortal", "0016_userdetail_trial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userdetail",
            name="ProfilePhoto",
            field=models.ImageField(
                default="ProfilePhoto/Default.png", upload_to="ProfilePhoto"
            ),
        ),
    ]
