# Generated by Django 4.2.7 on 2023-11-18 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("WhatsafPortal", "0017_alter_userdetail_profilephoto"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userdetail",
            old_name="Monthly",
            new_name="AlphaPremium",
        ),
        migrations.RenameField(
            model_name="userdetail",
            old_name="Yearly",
            new_name="GigaPremium",
        ),
        migrations.AddField(
            model_name="feature",
            name="AlphaPremium",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="feature",
            name="GigaPremium",
            field=models.BooleanField(default=False),
        ),
    ]
