# Generated by Django 4.2.7 on 2023-11-19 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("WhatsafPortal", "0018_rename_monthly_userdetail_alphapremium_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Newsletter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Email", models.EmailField(max_length=100)),
            ],
        ),
    ]
