# Generated by Django 4.2.7 on 2023-11-19 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("WhatsafPortal", "0019_newsletter"),
    ]

    operations = [
        migrations.AddField(
            model_name="userdetail",
            name="Active",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userdetail",
            name="BrowserID",
            field=models.CharField(default="", max_length=100),
        ),
    ]
