# Generated by Django 4.2.7 on 2023-12-23 15:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("WhatsafPortal", "0021_feature_short"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserWhatsAppDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("UserPP", models.CharField(max_length=500)),
                ("UserAbout", models.CharField(max_length=500)),
                ("UserLastSeenSetting", models.BooleanField()),
                ("UserOnlineStatusSetting", models.BooleanField()),
                ("UserReadRecipents", models.BooleanField()),
                ("UserDisapperingMessageSetting", models.BooleanField()),
                ("UserBlockedContacts", models.CharField(choices=[], max_length=500)),
                ("UserContact", models.CharField(choices=[], max_length=500)),
                ("UserContactPP", models.CharField(max_length=500)),
                (
                    "User",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="UserWhatsAppDetail",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
