# Generated by Django 4.2.7 on 2023-12-23 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("WhatsafPortal", "0022_userwhatsappdetail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userwhatsappdetail",
            name="UserBlockedContacts",
            field=models.CharField(
                choices=[("Blocked Contacts", "Blocked Contacts")], max_length=500
            ),
        ),
        migrations.AlterField(
            model_name="userwhatsappdetail",
            name="UserContact",
            field=models.CharField(choices=[("Contacts", "Contacts")], max_length=500),
        ),
    ]
