# Generated by Django 4.2.7 on 2023-12-23 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("WhatsafPortal", "0023_alter_userwhatsappdetail_userblockedcontacts_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userwhatsappdetail",
            name="UserAbout",
        ),
        migrations.RemoveField(
            model_name="userwhatsappdetail",
            name="UserBlockedContacts",
        ),
        migrations.RemoveField(
            model_name="userwhatsappdetail",
            name="UserContactPP",
        ),
        migrations.RemoveField(
            model_name="userwhatsappdetail",
            name="UserDisapperingMessageSetting",
        ),
        migrations.RemoveField(
            model_name="userwhatsappdetail",
            name="UserLastSeenSetting",
        ),
        migrations.RemoveField(
            model_name="userwhatsappdetail",
            name="UserOnlineStatusSetting",
        ),
        migrations.RemoveField(
            model_name="userwhatsappdetail",
            name="UserPP",
        ),
        migrations.RemoveField(
            model_name="userwhatsappdetail",
            name="UserReadRecipents",
        ),
    ]
