# Generated by Django 4.2.7 on 2023-12-24 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("WhatsafPortal", "0026_alter_userwhatsappdetail_usercontact"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userwhatsappdetail",
            name="UserContact",
            field=models.CharField(choices=[("Contact", "Contact")], max_length=500),
        ),
    ]
