# Generated by Django 4.2.7 on 2023-12-24 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("WhatsafPortal", "0027_alter_userwhatsappdetail_usercontact"),
    ]

    operations = [
        migrations.AddField(
            model_name="userwhatsappdetail",
            name="UserAbout",
            field=models.CharField(default="", max_length=500),
        ),
        migrations.AddField(
            model_name="userwhatsappdetail",
            name="UserBlockedContacts",
            field=models.CharField(
                choices=[("BlockedContacts", "BlockedContacts")],
                default="",
                max_length=500,
            ),
        ),
        migrations.AddField(
            model_name="userwhatsappdetail",
            name="UserContactPP",
            field=models.CharField(default="", max_length=500),
        ),
        migrations.AddField(
            model_name="userwhatsappdetail",
            name="UserDisapperingMessageSetting",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userwhatsappdetail",
            name="UserLastSeenSetting",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userwhatsappdetail",
            name="UserOnlineStatusSetting",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userwhatsappdetail",
            name="UserPP",
            field=models.CharField(default="", max_length=500),
        ),
        migrations.AddField(
            model_name="userwhatsappdetail",
            name="UserReadRecipents",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="userwhatsappdetail",
            name="UserContact",
            field=models.CharField(
                choices=[("Contacts", "Contacts")], default="", max_length=500
            ),
        ),
    ]
