# Generated by Django 4.2.7 on 2023-12-24 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("WhatsafPortal", "0029_userwhatsappdetail_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userwhatsappdetail",
            name="UserContactPP",
            field=models.CharField(
                choices=[("ContactsProfilePhoto", "ContactsProfilePhoto")],
                default="",
                max_length=500,
            ),
        ),
    ]
