# Generated by Django 4.2.7 on 2023-12-24 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("WhatsafPortal", "0030_alter_userwhatsappdetail_usercontactpp"),
    ]

    operations = [
        migrations.AddField(
            model_name="userwhatsappdetail",
            name="UserAboutExcluded",
            field=models.CharField(
                choices=[("AboutExcluded", "AboutExcluded")], default="", max_length=500
            ),
        ),
        migrations.AddField(
            model_name="userwhatsappdetail",
            name="UserLastSeenExcluded",
            field=models.CharField(
                choices=[("LastSeenExcluded", "LastSeenExcluded")],
                default="",
                max_length=500,
            ),
        ),
        migrations.AddField(
            model_name="userwhatsappdetail",
            name="UserPPExclusion",
            field=models.CharField(
                choices=[("ProfilePhotoExcluded", "ProfilePhotoExcluded")],
                default="",
                max_length=500,
            ),
        ),
    ]
